#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pandas as pd
from sqlalchemy import create_engine
import pyodbc
import datetime

# =============================================================================
# Variables received from user input || Alle i denne variabel sektion skal laves om til brugerinput
# =============================================================================
input_request_type = 0
input_report_type = 0
input_order_no = '030748'
input_pdf = 1
input_excel = 1
input_recipients = 'nmo@bki.dk'
# =============================================================================
# Variables generated by script without user input
# =============================================================================
Request_id = int(now.timestamp())
Server_ = 'sqlsrv04'
Db = 'BKI_Datastore'
Con = pyodbc.connect('DRIVER={SQL Server};SERVER=' + server + ';DATABASE=' + db)


def request_insert(dataframe):
    asd

